START TRANSACTION;

CREATE TABLE "Levels" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Levels" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "NickName" text NULL,
    "Email" text NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Courses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "CreatedById" integer NOT NULL,
    "LastUpdatedDate" timestamp with time zone NULL,
    "LastUpdatedById" integer NULL,
    "Level" integer NOT NULL,
    CONSTRAINT "PK_Courses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Courses_Users_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Courses_Users_LastUpdatedById" FOREIGN KEY ("LastUpdatedById") REFERENCES "Users" ("Id")
);

CREATE TABLE "Students" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_Students" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Students_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Lessons" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "CourseId" integer NOT NULL,
    CONSTRAINT "PK_Lessons" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Lessons_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES "Courses" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CourseStudent" (
    "CoursesId" integer NOT NULL,
    "StudentsId" integer NOT NULL,
    CONSTRAINT "PK_CourseStudent" PRIMARY KEY ("CoursesId", "StudentsId"),
    CONSTRAINT "FK_CourseStudent_Courses_CoursesId" FOREIGN KEY ("CoursesId") REFERENCES "Courses" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CourseStudent_Students_StudentsId" FOREIGN KEY ("StudentsId") REFERENCES "Students" ("Id") ON DELETE CASCADE
);

INSERT INTO "Levels" ("Id", "Name")
VALUES (0, 'Junior');
INSERT INTO "Levels" ("Id", "Name")
VALUES (1, 'Middle');
INSERT INTO "Levels" ("Id", "Name")
VALUES (2, 'Senior');

INSERT INTO "Users" ("Id", "Email", "FirstName", "LastName", "NickName")
VALUES (1, 'A@A.A', 'A_first', 'A_second', 'A_nick');
INSERT INTO "Users" ("Id", "Email", "FirstName", "LastName", "NickName")
VALUES (2, 'B@B.B', 'B_first', 'B_second', 'B_nick');
INSERT INTO "Users" ("Id", "Email", "FirstName", "LastName", "NickName")
VALUES (3, 'C@C.C', 'C_first', 'C_second', 'C_nick');
INSERT INTO "Users" ("Id", "Email", "FirstName", "LastName", "NickName")
VALUES (4, 'D@D.D', 'D_first', 'D_second', 'D_nick');
INSERT INTO "Users" ("Id", "Email", "FirstName", "LastName", "NickName")
VALUES (5, 'E@E.E', 'E_first', 'E_second', 'E_nick');

INSERT INTO "Courses" ("Id", "CreatedById", "CreatedDate", "Description", "LastUpdatedById", "LastUpdatedDate", "Level", "Name")
VALUES (1, 1, TIMESTAMPTZ '2023-08-22 21:00:00Z', 'The 1st Course Description', NULL, NULL, 0, 'The 1st Course');
INSERT INTO "Courses" ("Id", "CreatedById", "CreatedDate", "Description", "LastUpdatedById", "LastUpdatedDate", "Level", "Name")
VALUES (2, 1, TIMESTAMPTZ '2023-08-22 21:00:00Z', 'The 2nd Course Description', NULL, NULL, 0, 'The 2nd Course');
INSERT INTO "Courses" ("Id", "CreatedById", "CreatedDate", "Description", "LastUpdatedById", "LastUpdatedDate", "Level", "Name")
VALUES (3, 1, TIMESTAMPTZ '2023-08-22 21:00:00Z', 'The 3th Course Description', NULL, NULL, 1, 'The 3th Course');
INSERT INTO "Courses" ("Id", "CreatedById", "CreatedDate", "Description", "LastUpdatedById", "LastUpdatedDate", "Level", "Name")
VALUES (4, 1, TIMESTAMPTZ '2023-08-22 21:00:00Z', 'The 4th Course Description', NULL, NULL, 1, 'The 4th Course');
INSERT INTO "Courses" ("Id", "CreatedById", "CreatedDate", "Description", "LastUpdatedById", "LastUpdatedDate", "Level", "Name")
VALUES (5, 1, TIMESTAMPTZ '2023-08-22 21:00:00Z', 'The 5th Course Description', NULL, NULL, 2, 'The 5th Course');

INSERT INTO "Students" ("Id", "UserId")
VALUES (1, 2);

INSERT INTO "Lessons" ("Id", "CourseId", "Description", "Name")
VALUES (1, 1, 'The First Lesson Descriprion', 'The First Lesson');
INSERT INTO "Lessons" ("Id", "CourseId", "Description", "Name")
VALUES (2, 2, 'The First Lesson Descriprion', 'The First Lesson');
INSERT INTO "Lessons" ("Id", "CourseId", "Description", "Name")
VALUES (3, 3, 'The First Lesson Descriprion', 'The First Lesson');
INSERT INTO "Lessons" ("Id", "CourseId", "Description", "Name")
VALUES (4, 4, 'The First Lesson Descriprion', 'The First Lesson');
INSERT INTO "Lessons" ("Id", "CourseId", "Description", "Name")
VALUES (5, 5, 'The First Lesson Descriprion', 'The First Lesson');

COMMIT;